#!/bin/sh
### BEGIN INIT INFO
# Provides:          defender
# Required-Start:    $all
# Required-Stop:    
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: defender daemon
# Description:       Starts the defender daemon with the user specified in
#                    /root/defender.
### END INIT INFO

# Author: Hao Tseng

case "$1" in
  start)
   /root/defender/defender.sh start
   ;;
  stop)
   /root/defender/defender.sh stop
   ;;
  restart)
   /root/defender/defender.sh stop
   /root/defender/defender.sh start
   ;;
  *)
   echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
   exit 2
   ;;
esac

exit 0

